# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0
  android: circleci/android@1.0.3

executors:
  mac:
    macos:
      xcode: 12.5.1

jobs:
  distribute_android:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - run:
          command: bundle exec fastlane beta
          working_directory: android

workflows:
  test_and_distribute:
    jobs:
      - node/test:
          version: '15.1'
          pkg-manager: yarn
      - node/run:
          name: eslint
          version: '15.1'
          pkg-manager: yarn
          yarn-run: lint
      - distribute_android
