# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0
  android: circleci/android@1.0.3

executors:
  mac:
    macos:
      xcode: 12.5.1

commands:
  install_gems:
    parameters:
      dir:
        default: .
        type: string
    steps:
      - restore_cache:
          key: bundle-{{ checksum "<<parameters.dir>>/Gemfile.lock" }}-{{ arch }}
      - run: 
          command: bundle install
          working_directory: <<parameters.dir>>
      - save_cache:
          key: bundle-{{ checksum "<<parameters.dir>>/Gemfile.lock" }}-{{ arch }}
          paths:
            - <<parameters.dir>>/vendor/bundle

jobs:
  distribute_android:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - checkout
      - node/install-packages
      - install_gems:
          dir: android
      - run:
          command: bundle exec fastlane beta
          working_directory: android

workflows:
  test_and_distribute:
    jobs:
      - node/test
      - node/run:
          name: eslint
          npm-run: lint
      - distribute_android
