# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0
  react-native: react-native-community/react-native@5.5.0

workflows:
  test_and_distribute:
    jobs:
      - node/test:
          version: '15.1'
          pkg-manager: yarn
      - node/run:
          version: '15.1'
          pkg-manager: yarn
          yarn-run: lint
